### ISSUE TITLE
 Command '['sh', 'resources/IOMMU-check.sh']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by konsumer** [JussiVJ/vfio-conf#1]
```
  File "./gui.py", line 31
    print(line,end="")
                  ^
SyntaxError: invalid syntax
```

**Comment by JussiVJ** [comment]
You need to run the program with python 3. I think I mentioned it in my reddit post but I'll make sure to add it to the readme.

**Comment by konsumer** [comment]
In python3 I get a different error:

```
Traceback (most recent call last):
  File "./gui.py", line 35, in <module>
    if "IOMMU enabled" not in str(subprocess.check_output(['sh', 'resources/IOMMU-check.sh'])):
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sh', 'resources/IOMMU-check.sh']' returned non-zero exit status 1.
```

When I run `resources/IOMMU-check.sh` manually, I get no output and exit status 1

**Comment by JussiVJ** [comment]
Sorry for taking so long to respond. Please send me the output of IOMMU-check.sh which is in the resources folder and tell what distro you are using.

**Comment by JussiVJ** [comment]
Closing this due to inactivity
